Improve commands

diff --git a/gogs b/gogs
--- a/gogs
+++ b/gogs
@@ -11,7 +11,6 @@ gogs_server="" # https://try.gogs.io
 gogs_server_envvar=GOGS_SERVER_URL
 gogs_server_filename=gogs-server-url.txt
 
-debug=1
 # utils ----------
 
 function configure {
@@ -147,19 +146,50 @@ function per-line {
 
 actions=$actions" get-org"
 function get-org {
-	syntax-help 1 "org-name" "$@"
+	syntax-help 1 "org-name property" "$@"
 	json=$(gogs-curl GET /orgs/$1)
-	if [ $debug -eq 1 ]; then
-		echo "$json"
-	else
-		echo "$json" | json-property "username"
+
+	if [[ ! -z $2 ]]; then
+		test=`echo "$json" | json-property "$2"`
+	else 
+		test=`echo "$json"`
 	fi
+
+	if [[ -z $test ]]; then
+		exit_code=1
+	else
+		exit_code=0
+	fi
+	
+	echo $test
+	return $exit_code
 }
 
 actions=$actions" create-org"
 function create-org {
 	syntax-help 1 "org-name" "$@"
-	gogs-curl POST /admin/users/administrator/orgs "{\"username\":\"$1\"}"
+
+	get-org $1 > /dev/null 2>&1
+	if [[ $? -eq 0 ]]; then
+		echo "org already exist"
+		exit_code=0
+	elif [[ $? -eq 1 ]]; then
+		output=`gogs-curl POST /admin/users/administrator/orgs "{\"userame\":\"$1\"}"`
+		
+		test=`echo "$output" | json-property "message"`
+		if [[ -z $test ]]; then
+			echo $output
+			exit_code=0
+		else
+			echo $output
+			exit_code=1
+		fi
+	else
+		echo "Cannot retrieve org"
+		exit_code=2
+	fi
+
+	return $exit_code
 }
 
 actions=$actions" create-org-repo"
@@ -209,10 +239,19 @@ function get-repo {
 	syntax-help 2 "user/org-name repo-name [property]" "$@"
 	json="$(gogs-curl GET /repos/$1/$2)"
 	if [ $debug -eq 1 ] || [ -z $3 ]; then
-		echo "$json"
+		test=`echo "$json"`
 	else
-		echo "$json" | json-property "$3"
+		test=`echo "$json" | json-property "$3"`
 	fi
+
+	if [[ -z $test ]]; then
+		exit_code=1
+	else
+		exit_code=0
+	fi
+
+	echo $test
+	return $exit_code
 }
 
 actions=$actions" enable-issues"
@@ -226,7 +265,28 @@ actions=$actions" -"
 actions=$actions" create-team"
 function create-team {
 	syntax-help 3 "org-name team-name description [permission: read/write/admin]" "$@"
-	gogs-curl POST /admin/orgs/$1/teams "{\"name\":\"$2\",\"description\":\"$3\",\"permission\":\"$4\"}"
+
+	get-team $1 $2 > /dev/null 2>&1
+	if [[ $? -eq 0 ]]; then
+		echo "org already exist"
+		exit_code=0
+	elif [[ $? -eq 1 ]]; then
+		output=`gogs-curl POST /admin/orgs/$1/teams "{\"name\":\"$2\",\"description\":\"$3\",\"permission\":\"$4\"}"`
+		
+		test=`echo "$output" | json-property "message"`
+		if [[ -z $test ]]; then
+			echo $output
+			exit_code=0
+		else
+			echo $output
+			exit_code=1
+		fi
+	else
+		echo "Cannot retrieve org"
+		exit_code=2
+	fi
+
+	return $exit_code
 }
 
 actions=$actions" list-teams"
@@ -240,15 +300,40 @@ function list-teams {
 	fi
 }
 
-actions=$actions" get-team-id"
-function get-team-id {
-	syntax-help 2 "org-name team-name" "$@"
-	teams="$(gogs-curl GET /orgs/$1/teams)"
-	if [ $debug -eq 1 ]; then
-		echo "$teams"
+actions=$actions" get-teams"
+function get-teams {
+	syntax-help 1 "org-name property" "$@"
+	json=$(gogs-curl GET /orgs/$1/teams)
+	test=`echo "$json"`
+
+	if [[ -z $test ]]; then
+		exit_code=1
 	else
-		echo -n $(echo "$teams" | split-json "}," "{" | grep "\"name\":\"$2\"" | json-property id)
+		exit_code=0
 	fi
+
+	echo $test
+	return $exit_code
+}
+
+actions=$actions" get-team"
+function get-team {
+	syntax-help 2 "org-name/repo-name team-name property" "$@"
+	json_teams=`get-teams $1`
+	if [ $debug -eq 1 ] || [ -z $3 ]; then
+		test=`echo -n $(echo "$json_teams" | split-json "}," "{" | grep "\"name\":\"$2\"")`
+	else
+		test=`echo -n $(echo "$json_teams" | split-json "}," "{" | grep "\"name\":\"$2\"" | json-property $3)`
+	fi
+
+	if [[ -z $test ]]; then
+		exit_code=1
+	else
+		exit_code=0
+	fi
+
+	echo $test
+	return $exit_code
 }
 
 actions=$actions" -"
@@ -256,7 +341,36 @@ actions=$actions" -"
 actions=$actions" add-collaborator"
 function add-collaborator {
 	syntax-help 3 "user/org-name repo-name user-name [permission: read/write/admin]" "$@"
-	gogs-curl PUT /repos/$1/$2/collaborators/$3 "{\"permission\":\"$4\"}"
+
+	get-repo $1 $2 > /dev/null 2>&1
+
+	if [[ $? -ne 0 ]]; then
+		echo "Cannot retrieve repository $1/$2, please ensure the repository already exist"
+		return 1
+	fi
+
+	get-user $1 > /dev/null 2>&1
+
+	if [[ $? -ne 0 ]]; then
+		echo "Cannot retrieve user $3, please ensure the user already exist"
+		return 1
+	fi
+
+	output=`gogs-curl PUT /repos/$1/$2/collaborators/$3 "{\"permission\":\"$4\"}"`
+	error=`echo "$output" | json-property "message"`
+
+	if [[ -z $error ]]; then
+		message=$output
+		exit_code=0
+	else
+		message="ERROR: $error"
+		exit_code=1
+	fi
+
+
+	echo $message
+	return $exit_code
+
 }
 
 actions=$actions" remove-collaborator"
@@ -280,8 +394,41 @@ actions=$actions" -"
 
 actions=$actions" add-team-member"
 function add-team-member {
-	syntax-help 2 "team-id user-name" "$@"
-	gogs-curl PUT /admin/teams/$1/members/$2
+	syntax-help 3 "org-name/repo-name team-name user-name" "$@"
+
+	get-user $3 > /dev/null 2>&1
+
+	if [[ $? -ne 0 ]]; then
+		echo "ERROR: user not found, please create if first"
+		exit_code=1
+	fi
+	
+	id=`get-team $1 $2 id`
+	if [[ $? -ne 0 ]]; then
+		echo "ERROR: team not found, please create if first"
+		exit_code=1
+	fi
+
+	members_list=`list-team-members $id`
+
+	if [[ " ${members_list[*]} " =~ " ${3} " ]]; then
+		message="user already exist"
+		exit_code=0
+	else
+		output=`gogs-curl PUT /admin/teams/$id/members/$3`
+		
+		error=`echo "$output"`
+		if [[ -z $error ]]; then
+			message="user $3 added to the team id $id"
+			exit_code=0
+		else
+			message="ERROR: $error"
+			exit_code=1
+		fi
+	fi
+
+	echo $message
+	return $exit_code
 }
 
 actions=$actions" remove-team-member"
@@ -295,10 +442,19 @@ function list-team-members {
 	syntax-help 1 "team-id" "$@"
 	json=$(gogs-curl GET /admin/teams/$1/members)
 	if [ $debug -eq 1 ]; then
-		echo "$json"
+		test=`echo "$json"`
 	else
-		echo "$json" | split-json "}," "{" | per-line "json-property username"
+		test=`echo "$json" | split-json "}," "{" | per-line "json-property username"`
 	fi
+
+	if [[ -z $test ]]; then
+		exit_code=1
+	else
+		exit_code=0
+	fi
+
+	echo $test
+	return $exit_code
 }
 
 actions=$actions" -"
@@ -317,35 +473,99 @@ function remove-team-repo {
 
 actions=$actions" get-user"
 function get-user {
-	syntax-help 1 "user-name" "$@"
+	syntax-help 1 "user-name property" "$@"
 	json=$(gogs-curl GET /users/$1)
-	if [ $debug -eq 1 ]; then
-		echo "$json"
+	if [ $debug -eq 1 ] || [ -z $2 ]; then
+		test=`echo "$json"`
 	else
-		echo "$json" | json-property "username"
+		test=`echo "$json" | json-property "$2"`
 	fi
+
+	if [[ -z $test ]]; then
+		exit_code=1
+	else
+		exit_code=0
+	fi
+
+	echo $test
+	return $exit_code
 }
 
 actions=$actions" create-user"
 function create-user {
 	syntax-help 3 "user-name email password" "$@"
-	gogs-curl POST /admin/users "{\"username\": \"$1\", \"email\": \"$2\", \"password\":\"$3\"}"
+
+	get-user $1 > /dev/null 2>&1
+
+	if [[ $? -eq 0 ]]; then
+		message="user $1 already exist"
+		exit_code=0
+	elif [[ $? -eq 1 ]]; then
+		output=`gogs-curl POST /admin/users "{\"username\": \"$1\", \"email\": \"$2\", \"password\":\"$3\"}"`
+		error=`echo "$output" | json-property "message"`
+		if [[ -z $error ]]; then
+			message=$output
+			exit_code=0
+		else
+			message="ERROR: $error"
+			exit_code=1
+		fi
+	else
+		message="ERROR: Cannot retrieve org"
+		exit_code=2
+	fi
+
+	echo $message
+	return $exit_code
 }
 
 actions=$actions" create-user-token"
 function create-user-token {
 	syntax-help 3 "user-name password token-name" "$@"
-	gogs-curl_basic POST "$1:$2" /users/$1/tokens "{\"name\":\"$3\"}"
+
+	get-user $1 > /dev/null 2>&1
+
+	if [[ $? -eq 0 ]]; then
+		output=`gogs-curl_basic POST "$1:$2" /users/$1/tokens "{\"name\":\"$3\"}"`
+		error=`echo "$output" | json-property "message"`
+
+		if [[ -z $error ]]; then
+			message=$output
+			exit_code=0
+		else
+			message="ERROR: $error"
+			exit_code=1
+		fi
+	else
+		message="Error: Cannot retrieve user"
+		exit_code=2
+	fi
+
+	echo $message
+	return $exit_code
 }
 
 actions=$actions" create-mirror"
 function create-mirror {
 	syntax-help 5 "clone-address repo-name uid private mirror [optionnal: user password]" "$@"
 	if [ -z "$6" ]; then
-		gogs-curl POST /repos/migrate "{\"clone_addr\": \"$1\", \"repo_name\": \"$2\", \"uid\": $3, \"private\": $4, \"mirror\": $5}"
+		output=`gogs-curl POST /repos/migrate "{\"clone_addr\": \"$1\", \"repo_name\": \"$2\", \"uid\": $3, \"private\": $4, \"mirror\": $5}"`
 	else
-		gogs-curl POST /repos/migrate "{\"clone_addr\": \"$1\", \"repo_name\": \"$2\", \"uid\": $3, \"private\": $4, \"mirror\": $5, \"auth_username\":\"$6\", \"auth_password\":\"$7\"}"
+		output=`gogs-curl POST /repos/migrate "{\"clone_addr\": \"$1\", \"repo_name\": \"$2\", \"uid\": $3, \"private\": $4, \"mirror\": $5, \"auth_username\":\"$6\", \"auth_password\":\"$7\"}"`
 	fi
+
+	error=`echo "$output" | json-property "message"`
+
+	if [[ -z $error ]]; then
+		message=$output
+		exit_code=0
+	else
+		message="ERROR: $error"
+		exit_code=1
+	fi
+
+	echo $message
+	return $exit_code
 }
 
 actions=$actions" -"
@@ -430,7 +650,7 @@ if [ $# -gt 0 ]; then
 	for a in $actions; do
 		if [ "$a" == "$action" ] && [ "$a" != "-" ]; then
 			run_action $action "$@"
-			exit 0
+			exit $?
 		fi
 	done
 	case $action in
